version: "3.8"

services:
  mariadb:
    container_name: mariadb-ub-grics
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=db
  myapp:
    container_name: myapp-ub-grics
    image: docker.io/bitnami/laravel:latest
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_DATABASE=db
    volumes:
      - './project:/app'
    depends_on:
      - mariadb  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-ub-grics
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
